### ISSUE TITLE
Store a permanent copy of the joint called VCF

### ISSUE THREAD

**Issue by MattWellie** [populationgenomics/production-pipelines#3]
Ref: https://github.com/populationgenomics/production-pipelines/blob/initial/pipelines/seqr_loader.py#L203

Context: 
- The joint-called VCF path currently writes the output into temp. Could we write this file instead into a long-term storage bucket. If an analyst fails to find conclusive diagnostic variation in Seqr, the only remaining data stored at the pipeline's conclusion is the multi-sample MatrixTable. 

Problem: 
- If we want to apply standard bioinformatic tools to the joint calls for a single family, we have to load then entire MT (could be 10s or 000s of samples) in order to subset out a single family. 
- From that MT we must regenerate a VCF format file, instead of subsetting the original VCF (a relatively light operation for BCFtools).

Resolution: 
- Alter the destination of this file to be in a permanent storage location

Potential Issues: 
- For some joint callsets this could be prohibitively large (requires some data about the size of the current VCFs we are discarding). 
- There would be long term costs associated with storing this file, but relative to the component CRAM files this will be a small % of overall storage costs

**Comment by vladsaveliev** [comment]
Thanks a lot for bringing this up!

It's actually quite cheap to subset samples from a matrix table, and due to lazy evaluation it doesn't require loading an entire matrix table. But I understand that for smaller rare diseased subset it's pretty cheep to store VCFs as well. 

Though those joint-called VCFs would be lacking annotations that we normally add into a matrix table (VEP, ClinVar, external AFs, etc). Do you think it would make sense to export and store an annotated VCF instead?

Will address this after the break!

**Comment by MattWellie** [comment]
@vladsaveliev 

All useful points! I'd like to have a discussion after the break about what to do. Keeping the VCF is useful, but would mean re-annotating. Re-creating a VCF could be best, so long as we won't lose any information in the transition.

I had wrong assumptions about how expensive the parsing of the MT would be, so I think playing around with some of these objects in test to get a better idea of things will be useful!
