### ISSUE TITLE
Replace MtToEs stages Dataproc cluster usage with Hail Batch

### ISSUE THREAD

**Issue by EddieLF** [populationgenomics/production-pipelines#800]
There are several good reasons to reduce our reliance on Dataproc clusters, but some important reasons are that they are less transparent than Hail Batch jobs, they require dedicated "start cluster", "submit to cluster", and "stop cluster" jobs to run their workflows, and are generally more cumbersome and less user friendly. 

Dataproc clusters have largely been eliminated from cpg workflows where possible, but one last holdout for them is in the [MtToEs](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/stages/seqr_loader.py#L232) stage, as well as the [MtToEsSv](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/stages/gatk_sv/gatk_sv_multisample_2.py#L840) and [MtToEsCnv](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/stages/gcnv.py#L605) stages. 

In each of these cases, the `dataproc_scripts/mt_to_es.py` script is invoked in the same way, to transform an existing Hail MatrixTable `mt` into a seqr ready elasticsearch index.

```python
script = (
     f'cpg_workflows/dataproc_scripts/mt_to_es.py '
     f'--mt-path {dataset_mt_path} '
     f'--es-index {index_name} '
     f'--done-flag-path {done_flag_path} '
     f'--es-password {es_password_string}'
)
...
j = dataproc.hail_dataproc_job(
      get_batch(),
      script,
      ...,
      depends_on=inputs.get_jobs(dataset)
)
```

We should look at improving this process by eliminating the Dataproc cluster. We should use Hail Batch to connect to the Elasticsearch cluster and write to it directly. The use of the plaintext es-password should also be removed.

**Comment by MattWellie** [comment]
Relevant: https://github.com/populationgenomics/hail/blob/eea6227f1c7b9b58971b21ab5cd199882bba8446/hail/python/hail/methods/impex.py#L3331-L3332
https://github.com/populationgenomics/hail/blob/eea6227f1c7b9b58971b21ab5cd199882bba8446/hail/src/main/scala/is/hail/io/ElasticsearchConnector.scala#L61

**Comment by MattWellie** [comment]
https://github.com/populationgenomics/production-pipelines/compare/MtToEs_outside_dataproc?expand=1

This is a first attempt at taking all the DataProc MT -> ES translation, and removing all the guff. It is theft for sure.

Instead of relying on the seqr-loading-pipelines code, this extracts only the parts we need:

---

- We currently import and use the HailElasticSearch client ([here](https://github.com/populationgenomics/seqr-loading-pipelines/blob/80aa073839cd423223b5f0c87508d558e4ffd1bf/hail_scripts/elasticsearch/hail_elasticsearch_client.py#L25))
- That's a few levels of inheritance away from the [ElasticSearchClient](https://github.com/populationgenomics/seqr-loading-pipelines/blob/80aa073839cd423223b5f0c87508d558e4ffd1bf/hail_scripts/elasticsearch/elasticsearch_client_v7.py#L23), which is just a thin class that calls some ES methods.
- The [HailElasticSearchClient](https://github.com/populationgenomics/seqr-loading-pipelines/blob/80aa073839cd423223b5f0c87508d558e4ffd1bf/hail_scripts/elasticsearch/hail_elasticsearch_client.py#L26-L46) we're importing from `seqr-loading-pipelines` contains a whole load of methods to use if the arguments have non-default values, but of the mostly null default arguments we only pass `row_ht` (table), `index_name`, `num_shards`, and `write_null_values=True`. The result is that almost the added code between the elastic search library and this `HailElasticSearchClient` is not used by us, so we can drop it.

**Comment by MattWellie** [comment]
- The current process takes an ES password in plain text as an argument, then spends 16 lines working out if we can find the password again ([here](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/dataproc_scripts/mt_to_es.py#L110-L126)). This becomes "use config variables to find a password, quit if unsuccessful" [here](https://github.com/populationgenomics/production-pipelines/blob/MtToEs_outside_dataproc/cpg_workflows/dataproc_scripts/mt_to_es_free_of_dataproc.py#L271-L279). Added bonus - no longer need to generate and pass a secret in advance, as we do [here](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/stages/seqr_loader.py#L252-L274)
- starts a non-local hail batch ([this](https://github.com/populationgenomics/production-pipelines/blob/main/cpg_workflows/dataproc_scripts/mt_to_es.py#L111) only works in DataProc as the relevant data is pseudo-localised), so now we do [this](https://github.com/populationgenomics/production-pipelines/blob/MtToEs_outside_dataproc/cpg_workflows/dataproc_scripts/mt_to_es_free_of_dataproc.py#L206)
- the methods `elasticsearch_row`, `_mt_num_shards`, and `_cleanup` are copied
- Instead of using the imported HailESClient and overriding some more methods, I've created a fresh class [here](https://github.com/populationgenomics/production-pipelines/blob/MtToEs_outside_dataproc/cpg_workflows/dataproc_scripts/mt_to_es_free_of_dataproc.py#L93). This contains all the methods that we used in the imported class, and none of the methods that would be triggered only if we overrode the default arguments - i.e. most of the logic [here](https://github.com/populationgenomics/seqr-loading-pipelines/blob/80aa073839cd423223b5f0c87508d558e4ffd1bf/hail_scripts/elasticsearch/hail_elasticsearch_client.py#L97-L208) is not executed when we use the client, so we don't need the relevant methods in our client
- We do use a number of methods to encode Hail Types as ES types, so I've copied in [the relevant constants](https://github.com/populationgenomics/production-pipelines/blob/MtToEs_outside_dataproc/cpg_workflows/dataproc_scripts/mt_to_es_free_of_dataproc.py#L16-L41) and the methods that use them

**Comment by MattWellie** [comment]
NGL, I don't really know how to test this without YOLO'ing all in, but if it works we can remove our dependency on the `seqr-loading-pipelines` submodule forever.

@illusional @EddieLF do we have a test ES instance for test-Seqr?

**Comment by illusional** [comment]
We don't @MattWellie, but it shouldn't really matter right? Just pick a matrix table, import it with some ES index name, and connect it in staging. @MattWellie, can you create a draft PR of those changes, make it easy to comment directly.

**Comment by EddieLF** [comment]
Solution looks great @MattWellie! Thanks for the rundown too.

We don't have a specific test ES instance for seqr-staging or seqr-reanalysis-dev. When we load ES Indices into these test projects, we have to give the seqr-staging / seqr-reanalysis-dev roles access to those specific indices via the ES kibana page.

In terms of writing to the ES cluster, I don't think there should be any issues even with a test account, so long as we provide the correct ES password and route
